### PR TITLE
Upgrade Ansible to upstream stable-2.0.0.1

### PR DESCRIPTION
**Pull request by zsais**
Direct requirements away from our fork and use the clean waters that is Ansible stable-2.0.0.1

### CODE REVIEW

**Comment by omgjlk** [comment]
I think we probably want to go a bit more generic in our ansible requirement, and not pin us to a specific version until we have a need to do that. Saves us needless churn if/when Ansible releases new versions of 2.x.

And we may want to just express the install direct from pypi instead of a git url.

**Comment by masteinhauser** [comment]
@zrs233 I agree on both points made by @j2sol above. Fix 'em up, and it otherwise looks good.

We will want to definitely tag a new release for ursula-cli for reference internally when we're able to upgrade projects.

**Comment by omgjlk** [comment]
Lets not merge this until we pin `ursula` and maybe `ursula-flotsam` to an older version of ursula-cli.

They aren't ready for the jump to 2.0 yet and they are using an unversioned requirement on ursula-cli.

**Comment by omgjlk** [comment]
This looks good to me know, but I'd like to see it kept on a feature branch until such time as all consumers are ready to make the jump to ansible 2.0.

**Comment by paulczar** [comment]
IMO we should merge this to master and pin ursula etc to a specific version of cli if it needs to continue to use 1.9.

**Comment by angstwad** [comment]
So I'd recommend two things:
1. We should internally pin to the 2.x series starting with 2.0.2.0 (because 2.0.2.0 fixes some important issues), and set a max, using the the following check and an updated error message:

```
In [24]: ANSIBLE_VERSION_MIN = LooseVersion('2.0.2.0')

In [25]: ANSIBLE_VERSION_MAX = LooseVersion('3.0')

In [26]: ANSIBLE_VERSION_MIN >= current_version < ANSIBLE_VERSION_MAX
Out[26]: True
```

...and 2. As soon as that's done, get this merged in ASAP so we can begin to use it.  Use of the Ansible 2.0 in Ursula will depend on this and a future PR from me, and before I can begin this needs to be merged.

**Comment by zsais** [comment]
Closing this PR in favor of https://github.com/blueboxgroup/ursula-cli/pull/34

**Pull request closed without merging**
